### ISSUE TITLE
Registration form

### ISSUE THREAD

**Issue by bolverk** [bolverk/racah_retreat_2017#9]
The registration form should have the following fields:
- Name
- Position (faculty, phd, msc etc)
- Phone number
- Email
- check boxes with dietary restrictions (Celiac, Vegan, vegetarian, kosher etc)
- radio buttons for pick up and drop off locations (givat ram campus, mevaseret, modi'in and an extra option for people who travel on their own).
- preferences for room mates
- Free text suggestion box

**Comment by ItaiLin** [comment]
There's a google form used in the previous retreat - it's in the google drive folder

**Comment by bolverk** [comment]
website created
https://sites.google.com/site/racahretreat2017/
